### ISSUE TITLE
Fixes for latest Zig

### ISSUE THREAD

**Issue by moderation** [zigtools/zls#1206] opened 2023-05-27 22:48 UTC
I made the following changes that allow for compilation with latest Zig. Commits that caused the break
- https://github.com/ziglang/zig/commit/ca16f1e8a703491bcaac0d13379d2556e8ca837d
- https://github.com/ziglang/zig/commit/4159add4abe92e903d8797a005344d8325def2fc

```diff
diff --git a/src/analyser/InternPool.zig b/src/analyser/InternPool.zig
index 050a885..ac3880e 100644
--- a/src/analyser/InternPool.zig
+++ b/src/analyser/InternPool.zig
@@ -452,8 +452,8 @@ pub const Key = union(enum) {
         var key: Key = ty;
         while (true) switch (key) {
             .simple_type => |simple| switch (simple) {
-                .usize => return .{ .signedness = .signed, .bits = target.cpu.arch.ptrBitWidth() },
-                .isize => return .{ .signedness = .unsigned, .bits = target.cpu.arch.ptrBitWidth() },
+                .usize => return .{ .signedness = .signed, .bits = target.ptrBitWidth() },
+                .isize => return .{ .signedness = .unsigned, .bits = target.ptrBitWidth() },
 
                 .c_char => return .{ .signedness = .signed, .bits = target.c_type_bit_size(.char) },
                 .c_short => return .{ .signedness = .signed, .bits = target.c_type_bit_size(.short) },
diff --git a/src/configuration.zig b/src/configuration.zig
index c5b5740..ee3ea53 100644
--- a/src/configuration.zig
+++ b/src/configuration.zig
@@ -261,7 +261,7 @@ pub fn findZig(allocator: std.mem.Allocator) !?[]const u8 {
         const file = std.fs.openFileAbsolute(full_path, .{}) catch continue;
         defer file.close();
         const stat = file.stat() catch continue;
-        if (stat.kind == .Directory) continue;
+        if (stat.kind == .directory) continue;
 
         return try allocator.dupe(u8, full_path);
     }
diff --git a/src/features/completions.zig b/src/features/completions.zig
index c4acbff..3f15e90 100644
--- a/src/features/completions.zig
+++ b/src/features/completions.zig
@@ -993,22 +993,22 @@ fn completeFileSystemStringLiteral(
                 else => unreachable,
             };
             switch (entry.kind) {
-                .File => if (expected_extension) |expected| {
+                .file => if (expected_extension) |expected| {
                     const actual_extension = std.fs.path.extension(entry.name);
                     if (!std.mem.eql(u8, actual_extension, expected)) continue;
                 },
-                .Directory => {},
+                .directory => {},
                 else => continue,
             }
 
             _ = try completions.getOrPut(arena, types.CompletionItem{
                 .label = try arena.dupe(u8, entry.name),
                 .detail = if (pos_context == .cinclude_string_literal) path else null,
-                .insertText = if (entry.kind == .Directory)
+                .insertText = if (entry.kind == .directory)
                     try std.fmt.allocPrint(arena, "{s}/", .{entry.name})
                 else
                     null,
-                .kind = if (entry.kind == .File) .File else .Folder,
+                .kind = if (entry.kind == .file) .File else .Folder,
             });
         }
     }
```

**Comment by travisstaloch** [comment] 2023-05-27 23:01
duplicate of #1205

**Closed by travisstaloch** 2023-05-27 23:01 UTC
Labels: enhancement
