### ISSUE TITLE
ZLS intellisense suggests duplicate declarations in complex namespace types

### ISSUE THREAD

**Issue by mbartelsm** [zigtools/zls#1891] opened 2024-05-09 21:53 UTC
### Zig Version

0.12.0

### Zig Language Server Version

0.12.0

### Client / Code Editor / Extensions

VSCode with Zig extension

### Steps to Reproduce and Observed Behavior

The following code
```zig
const S = struct {
    pub fn foo() void {}
};

const S1 = struct {
    pub const a: i32 = 0;
};

const S2 = struct {
    pub const a: u8 = 0;
};

fn S3(comptime opt: bool) type {
    return if (opt) struct {
        pub usingnamespace S;
        pub usingnamespace S1;
    }
    else struct {
        pub usingnamespace S;
        pub usingnamespace S2;
    };
}

pub fn main() !void {
    _ = S3(true). // <<< Autocomplete here
}

```

Will produce duplicate suggestions.

![image](https://github.com/zigtools/zls/assets/5376208/32f5a510-9892-4020-8bea-fae83219630f)

If you use more complex branching, every possibility will be added, resulting in even more duplicates

![image](https://github.com/zigtools/zls/assets/5376208/692fbf7f-b709-4b1b-99c1-fc3ce99f72c5)

### Expected Behavior

I would expect duplicates to be filtered out.

By a duplicate I mean a declaration of matching name and type. I believe there is merit in keeping declarations of matching name but different type as, barring more sophisticated type evaluation, an overview of all the available types is better than a single wrong one.

Alternatively, "unknown" or the most general type (`i32` and `u8` => `Int`, or `fn () void` and `fn (bool) !Bar` => `Fn`) could be specified instead

**Comment by Techatrix** [comment] 2024-05-25 20:42
Duplicate of #1041

**Closed by Techatrix** 2024-05-25 20:42 UTC
Labels: bug
