### ISSUE TITLE
Release windows binaries as .zip files

### ISSUE THREAD

**Issue by SpexGuy** [zigtools/zls#808] opened 2022-12-05 06:38 UTC
zst is not a format that most windows users can decompress easily.  Even 7zip, afaict the most widely installed third party decompression tool on windows, can't open them.  For the windows binaries in releases to be useful, they should be released in a format that windows users can use.  Preferably .zip, which can be decompressed directly from the OS's file explorer.

The zstd project does have windows executables in its releases, but it's a bit silly IMO to require users to download this oddly specific project to use ZLS.

**Comment by SuperAuguste** [comment] 2022-12-05 19:17
Feel free to PR this change :)

**Comment by SuperAuguste** [comment] 2022-12-06 00:53
We don't send over any compressed archives to Felix, so yep it's all good.

**Comment by Techatrix** [comment] 2023-06-23 11:15
The [0.10.0](https://github.com/zigtools/zls/releases/tag/0.10.0) Release is shipping zstd compressed tarballs on all architectures.

**Comment by Techatrix** [comment] 2023-08-16 14:56
duplicate of https://github.com/zigtools/zls/issues/407
the latest ZLS 0.11.0 release now ships .zip files for windows

**Closed by Techatrix** 2023-08-16 14:56 UTC
Labels: enhancement
