### ISSUE TITLE
Merged Error Sets are not desblayed correctrly in the inlay hints.

### ISSUE THREAD

**Issue by PaNDa2code** [zigtools/zls#1950] opened 2024-07-13 16:53 UTC
### Zig Version

0.14.0-dev.121+ab4c461b7

### Zig Language Server Version

fbd8b9a87a3cd5ab8389054815d9e3f81dfd430b

### Steps to Reproduce and Observed Behavior

When using ![Merged Error Sets](https://ziglang.org/documentation/master/#Merging-Error-Sets), the inlay hints are displayed incorrectly. Instead of appearing next to the relevant code, they are shown at the right-hand side of the source code, causing readability issues.

![Screenshot_2024-07-13_18_17_00](https://github.com/user-attachments/assets/7732d9d4-3c33-4683-b546-8ad6a84e0498)

![Screenshot_2024-07-13_18_15_48](https://github.com/user-attachments/assets/177fa8a2-ba09-4268-afb1-58a3a37b1c3a)

### Expected Behavior

I think the proper behavior is to show the name of the merged error set like in the (non-merged error sets) 

![Screenshot_2024-07-13_18_50_01](https://github.com/user-attachments/assets/7b9cbfaf-1956-4021-b666-3880823dbb15)

**Comment by Techatrix** [comment] 2024-07-14 23:28
duplicate of #1828

**Closed by Techatrix** 2024-07-14 23:28 UTC
Labels: bug
