### ISSUE TITLE
 Array and slice prompts are wrong

### ISSUE THREAD

**Issue by zhang-chuanfeng** [zigtools/zls#1538] opened 2023-10-20 15:20 UTC
### Zig Version

0.12.0-dev.1127+32bc07767

### Zig Language Server Version

0.12.0-dev.152+1a282b3

### Steps to Reproduce

As shown below

![image](https://github.com/zigtools/zls/assets/59160162/0953dcb1-9007-43bd-a95d-771e6bcadf6b)

should be `*[_]i32` not `[]i32` 

### Expected Behavior

should be `*[_]i32` 

### Actual Behavior

`[]i32`

**Comment by Techatrix** [comment] 2023-10-21 10:02
duplicate of #1230.

**Closed by Techatrix** 2023-10-21 10:02 UTC
Labels: bug
