### ISSUE TITLE
Incorrect Type Hint for Nested Array Lists

### ISSUE THREAD

**Issue by DonIsaac** [zigtools/zls#2070] opened 2024-10-31 15:06 UTC
### Zig Version

0.13.0

### ZLS Version

0.13.0

### Client / Code Editor / Extensions

nvim v0.11.0-dev with CoC.nvim 0.0.82

From `:CocInfo`:
```
vim version: NVIM v0.11.0-dev
node version: v22.8.0
coc.nvim version: 0.0.82-9fd85781 2024-09-21 00:59:00 +0900
coc.nvim directory: /home/donisaac/.vim/plugged/coc.nvim
term: xterm-kitty
platform: linux
```

### Steps to Reproduce and Observed Behavior

Occurs when using an unmanaged array list containing other unmanaged array lists (e.g. `std.ArrayListUnmanaged(std.ArrayListUnmanaged(u32))`. 
Calling `addOne` on the outer list provides a type hint for the `T` of the inner list. 

> [Compiler Explorer](https://godbolt.org/z/E9E786o5b)

![image](https://github.com/user-attachments/assets/384bfb76-93ca-42f4-a800-f54675b9bed3)

### Expected Behavior

```zig
const list: std.ArrayListUnmanaged(std.ArrayListUnmanaged(u32)) = .{}
// Type hint should be *std.ArrayListUnmanaged(u32)
// but is instead *u32
const sublist = list.addOne(alloc);
```

**Comment by Techatrix** [comment] 2024-10-31 15:09
Duplicate of  #1392

**Closed by Techatrix** 2024-10-31 15:09 UTC
Labels: bug
