### ISSUE TITLE
zls crashes when there is unicode characters outside a comment

### ISSUE THREAD

**Issue by IntegratedQuantum** [zigtools/zls#1151] opened 2023-04-23 17:35 UTC
### Zig Version

0.11.0-dev.2336+5b82b4004

### Zig Language Server Version

471d971d1d2e6be5a9e2b3b678656038c50ade2e

### Steps to Reproduce

I just pasted this formula into the code(outside a comment):
```zig
1 - 2916/125*x² - 16038/125*x⁴ + 268272/125*x⁶ - 629856/125*x⁸
```
(Note the unicode character ² ⁴ ⁶ ⁸)

### Expected Behavior

zls should not crash, even on illegal code.

### Actual Behavior

It crashed with stack trace:
```
thread 12289 panic: index out of bounds: index 17, len 16
/home/mint/Downloads/zig/lib/std/unicode.zig:271:24: 0x652b25 in nextCodepointSlice (zls)
        return it.bytes[it.i - cp_len .. it.i];
                       ^
/home/mint/Downloads/zig/lib/std/unicode.zig:275:44: 0x580077 in nextCodepoint (zls)
        const slice = it.nextCodepointSlice() orelse return null;
                                           ^
/home/mint/zls/src/offsets.zig:311:38: 0x57fec0 in countCodeUnits (zls)
            while (iter.nextCodepoint()) |codepoint| {
                                     ^
/home/mint/zls/src/offsets.zig:107:31: 0x4e6770 in locLength (zls)
    return countCodeUnits(text[loc.start..loc.end], encoding);
                              ^
/home/mint/zls/src/offsets.zig:299:45: 0x45c28e in advancePosition (zls)
        .character = @intCast(u32, locLength(text, line_loc, encoding)),
                                            ^
/home/mint/zls/src/features/folding_range.zig:102:116: 0x51cf31 in getRanges (zls)
            const position = offsets.advancePosition(builder.tree.source, last_position, last_index, index, builder.encoding);
                                                                                                                   ^
/home/mint/zls/src/features/folding_range.zig:321:33: 0x485acc in generateFoldingRanges (zls)
    return try builder.getRanges();
                                ^
/home/mint/zls/src/Server.zig:1208:82: 0x41de64 in foldingRangeHandler (zls)
    return try folding_range.generateFoldingRanges(allocator, handle.tree, server.offset_encoding);
                                                                                 ^
/home/mint/zls/src/Server.zig:1510:35: 0x3d7620 in processMessage (zls)
                break :blk handler(server, params) catch |err| {
                                  ^
/home/mint/zls/src/Server.zig:1367:26: 0x37cbfa in processJsonRpc (zls)
    server.processMessage(message) catch |err| switch (message) {
                         ^
/home/mint/zls/src/main.zig:81:30: 0x37c38b in loop (zls)
        server.processJsonRpc(json_message);
                             ^
/home/mint/zls/src/main.zig:396:13: 0x37d788 in main (zls)
    try loop(server, record_file, replay_file);
            ^
/home/mint/Downloads/zig/lib/std/start.zig:617:37: 0x364c8e in posixCallMainAndExit (zls)
            const result = root.main() catch |err| {
                                    ^
/home/mint/Downloads/zig/lib/std/start.zig:376:5: 0x3646f1 in _start (zls)
    @call(.never_inline, posixCallMainAndExit, .{});
    ^
```

**Comment by travisstaloch** [comment] 2023-04-23 18:34
I had a similar bug fixed in [this commit](https://github.com/travisstaloch/diff-zimilar/commit/8ae05e74f11503d632cb5436503652aaf01abb12)

Here is how it looks now: https://github.com/travisstaloch/diff-zimilar/blob/main/src/range.zig#L57

**Comment by travisstaloch** [comment] 2023-05-05 23:25
@IntegratedQuantum I can't reproduce the panic you were seeing when pasting the that formula into my editor (sublime on linux).  Maybe if you can reproduce, you could test-drive https://github.com/zigtools/zls/pull/1171 and see if it fixes things.

**Comment by IntegratedQuantum** [comment] 2023-05-06 08:17
> I can't reproduce the panic you were seeing when pasting the that formula into my editor (sublime on linux). Maybe if you can reproduce, you could test-drive https://github.com/zigtools/zls/pull/1171 and see if it fixes things.

The fix is working for me(I'm using VSCode on linux).

**Comment by travisstaloch** [comment] 2023-05-06 08:25
were you also able to reproduce the crash with the current zls? i've heard some of these utf8 bugs may not reproduce reliably.

**Comment by IntegratedQuantum** [comment] 2023-05-06 08:28
Yes. I can reliably reproduce it with the current master version.

**Comment by travisstaloch** [comment] 2023-05-06 08:37
Oh good. I've just been able to reproduce w/ vscode too! But i found that just pasting the formula into a zig file isn't enough.  It needs to be in a test block and w/ a valid decl prefix (`const x = `) and trailing semicolon:
```zig
test {
    const x = 1 - 2916/125*x² - 16038/125*x⁴ + 268272/125*x⁶ - 629856/125*x⁸;
}
```

**Closed** 2023-07-29 21:14 UTC
Labels: bug
