### ISSUE TITLE
Lots of `usingnamespace` makes ZLS crash-prone

### ISSUE THREAD

**Issue by expikr** [zigtools/zls#1603] opened 2023-11-14 21:18 UTC
So I've been experimenting with generics and polymorphism with the code posted in the following:

https://github.com/nektro/zigquestions/issues/9

ZLS seems to become very brittle whenever I'm making changes to that code. If I refactor a name, VSCode will tell me that "ZLS had crashed five times within the last three minutes and will not restart because restarted" within two seconds while I'm in the middle of typing it out.

**Comment by Techatrix** [comment] 2023-11-15 00:19
Could you please provide the necessary information from the bug report [template](https://github.com/zigtools/zls/issues/new?assignees=&labels=bug&projects=&template=bug.yml) which needs the following information:
- Zig Version
- Zig Language Server Version
- Steps to Reproduce (What exactly can someone else do, in order to observe the problem that you observed?)
- ~~Expected Behavior~~ (no crash obviously)
- Actual Behavior (ZLS's [log ouput](https://github.com/zigtools/zls/wiki/Guide:-How-to-view-ZLS-log-output) which should include a stack trace when ZLS is a debug build)

**Comment by Techatrix** [comment] 2023-11-15 00:29
> How do you find the version from VSCode?

You should find the path to ZLS in the [log ouput](https://github.com/zigtools/zls/wiki/Guide:-How-to-view-ZLS-log-output) or in the `zig.zls.path` option in VSCode.

**Comment by Techatrix** [comment] 2023-11-15 00:37
I've managed to reproduce your with ZLS 0.11.0. This doesn't happen anymore in ZLS master so it has been fixed at some point.

**Comment by Techatrix** [comment] 2023-11-15 00:39
> This?

Yes, I should have mentioned that you can the pass the `--version` flag to ZLS to get the version from it. Isn't necessary anymore because your log output also includes the version which was 0.11.0.

**Comment by Techatrix** [comment] 2023-11-15 00:56
> What do you imagine might be the cause?

ZLS crashes because infinite recursion when doing a symbol lookup through `usingnamespace`s.

<details>
<summary>Call Stack</summary>

```
#0  0x00000000007a727c in hash.auto_hash.hash__anon_82801 (hasher=0x7ffff3fca710, key=157)
    at /nix/store/hzv7x0xwfw8912kib3x8jpcly9ar1ng9-zig-0.12.0-dev.3+9c05810be/lib/std/hash/auto_hash.zig:73
#1  0x00000000007019e4 in hash.auto_hash.autoHash__anon_77664 (hasher=0x7ffff3fca710, key=157)
    at /nix/store/hzv7x0xwfw8912kib3x8jpcly9ar1ng9-zig-0.12.0-dev.3+9c05810be/lib/std/hash/auto_hash.zig:203
#2  0x000000000065bec7 in analysis.NodeWithUri.Context.hash (item=...) at analysis.zig:1959
#3  0x00000000007a628d in hash_map.HashMapUnmanaged(analysis.NodeWithUri,void,analysis.NodeWithUri.Context,80).getOrPutAssumeCapacityAdapted__anon_82795 (self=0x7ffff4fa6f30, key=...) at /nix/store/hzv7x0xwfw8912kib3x8jpcly9ar1ng9-zig-0.12.0-dev.3+9c05810be/lib/std/hash_map.zig:1319
#4  0x0000000000700fc0 in hash_map.HashMapUnmanaged(analysis.NodeWithUri,void,analysis.NodeWithUri.Context,80).getOrPutContextAdapted__anon_77634 (
    self=0x7ffff4fa6f30, allocator=..., key=...) at /nix/store/hzv7x0xwfw8912kib3x8jpcly9ar1ng9-zig-0.12.0-dev.3+9c05810be/lib/std/hash_map.zig:1299
#5  0x000000000065ba3f in hash_map.HashMapUnmanaged(analysis.NodeWithUri,void,analysis.NodeWithUri.Context,80).getOrPutContext (self=0x7ffff4fa6f30, 
    allocator=<error reading variable: Cannot access memory at address 0x7>, key=...)
    at /nix/store/hzv7x0xwfw8912kib3x8jpcly9ar1ng9-zig-0.12.0-dev.3+9c05810be/lib/std/hash_map.zig:1276
#6  0x00000000005ca4b9 in hash_map.HashMapUnmanaged(analysis.NodeWithUri,void,analysis.NodeWithUri.Context,80).getOrPut (self=0x7ffff4fa6f30, 
    allocator=<error reading variable: Cannot access memory at address 0x7>, key=...)
    at /nix/store/hzv7x0xwfw8912kib3x8jpcly9ar1ng9-zig-0.12.0-dev.3+9c05810be/lib/std/hash_map.zig:1273
#7  0x000000000054bd5e in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3044
#8  0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#9  0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#10 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#11 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#12 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#13 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#14 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#15 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#16 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#17 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#19 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#20 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#21 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#22 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#23 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#24 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#25 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#26 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#27 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#28 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#29 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#30 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#31 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#32 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#33 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#34 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#35 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#36 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#37 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#38 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#39 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#40 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
--Type <RET> for more, q to quit, c to continue without paging--
#41 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#42 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#43 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#44 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#45 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#46 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#47 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#48 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#49 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#50 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#51 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#52 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#53 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#54 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#55 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#56 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#57 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#58 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#59 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
    at analysis.zig:3144
#60 0x00000000004f0f5a in analysis.TypeWithHandle.lookupSymbol (self=..., analyser=0x7ffff4fa6ed0, symbol=...) at analysis.zig:1876
#61 0x000000000054c01d in analysis.resolveUse (analyser=0x7ffff4fa6ed0, uses=..., symbol=..., handle=0x7ffff3fb3000) at analysis.zig:3058
#62 0x00000000005513fc in analysis.lookupSymbolContainer (analyser=0x7ffff4fa6ed0, container_handle=..., symbol=..., kind=variable)
```
This goes on for a few thousand more lines.
</details>

**Comment by Techatrix** [comment] 2023-11-16 20:04
Since this has been fixed in master, there is nothing to do here so I will close this issue.

**Closed by Techatrix** 2023-11-16 20:04 UTC
