### ISSUE TITLE
Wrong type given on `items` of nested `ArrayListUnmanaged`

### ISSUE THREAD

**Issue by DivergentClouds** [zigtools/zls#1609] opened 2023-11-18 19:47 UTC
### Zig Version

0.12.0-dev.1643+91329ce94

### Zig Language Server Version

e89b712e69baa7f745d2d146ca3231264978f1d6

### Steps to Reproduce

Paste this code in your editor and look at the type given in the docs (`k` in space mode for Helix) for the `.items` on line 14 and compare with the value given when the program is run.
```zig
const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();

    const allocator = gpa.allocator();

    var list_of_list_unmanaged = try std.ArrayListUnmanaged(
        std.ArrayListUnmanaged(u8),
    ).initCapacity(allocator, 0);
    defer list_of_list_unmanaged.deinit(allocator);

    std.debug.print("{}\n", .{@TypeOf(list_of_list_unmanaged.items)});
}
```

### Expected Behavior

The type shown should be `[]array_list.ArrayListAlignedUnmanaged(...)`.

### Actual Behavior

The type shown is `[]u8`.

![image](https://github.com/zigtools/zls/assets/27089165/b454063b-80ec-45c5-8563-7c4268b29393)

**Comment by DivergentClouds** [comment] 2023-11-18 19:51
Note that if the outer ArrayList is managed it works as it should. 
![image](https://github.com/zigtools/zls/assets/27089165/6f091097-5870-45de-91de-41e32088aa8d)

**Comment by leecannon** [comment] 2023-11-18 19:58
Duplicate of #1392

**Closed by leecannon** 2023-11-18 19:58 UTC
Labels: bug
