### ISSUE TITLE
Imports aren't identified if artifacts aren't created

### ISSUE THREAD

**Issue by akhildevelops** [zigtools/zls#2010] opened 2024-08-22 17:26 UTC
### Zig Version

0.13.0

### ZLS Version

0.13.0

### Client / Code Editor / Extensions

VSCode

### Steps to Reproduce and Observed Behavior

For below build.zig,

```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const postgres_module = b.dependency("pg", .{}).module("pg");
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addExecutable(.{ .name = "see_cleverly", .root_source_file = b.path("src/main.zig"), .target = target, .optimize = optimize });
    lib.root_module.addImport("pg", postgres_module);

    // b.installArtifact(lib); 
}

```
`pg` is not identified by zls

![image](https://github.com/user-attachments/assets/dd95d549-22dd-47eb-9bb6-748506ea6a81)

Below `build.zig` works
```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const postgres_module = b.dependency("pg", .{}).module("pg");
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addExecutable(.{ .name = "see_cleverly", .root_source_file = b.path("src/main.zig"), .target = target, .optimize = optimize });
    lib.root_module.addImport("pg", postgres_module);

    b.installArtifact(lib);
}
```

![image](https://github.com/user-attachments/assets/78a615ec-af4e-4eab-958b-92f50994aa2b)

Why would installartifact matter for zls to identify imported module ?

Below `build.zig` also doesn't work if I treat zig application as just a dependency to be imported by others
```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const postgres_module = b.dependency("pg", .{}).module("pg");
    const module = b.addModule("see_cleverly", .{ .root_source_file = b.path("src/main.zig") });
    module.addImport("pg", postgres_module);
}

```

### Expected Behavior

Imports should be recognized by zls

**Comment by taylorh140** [comment] 2024-08-22 20:49
I'm getting the same behavior. Is there any workarounds?

**Comment by akhildevelops** [comment] 2024-08-23 01:07
Workaround is to add add this in your build.zig `b.installArtifact(lib);`

**Comment by Techatrix** [comment] 2024-08-25 13:00
> Why would installartifact matter for zls to identify imported module ?

Declaring a compile step with `b.addExecutable` on its own has no side-effects. Every step needs to be reachable from a top-level-step like `install` `test` `check` etc. Calling `b.installArtifact` is one possible approach because it declares the compile step as a dependency of the `install` step. A step that is not reachable from a top-level-step is the equivalent of an unused variable. You never actually compiling your `src/main.zig` so why should ZLS know about it?

This is working as intended. Even if ZLS would want to handle this, there is no way to figure out that you declared an unused step. [If a tree falls in a forest and no one is around to hear it, does it make a sound?](https://en.wikipedia.org/wiki/If_a_tree_falls_in_a_forest_and_no_one_is_around_to_hear_it%2C_does_it_make_a_sound%3F)

Declaring a module with `b.addModule` on the other hand is has side-effects since it makes the module accessible to other project via `b.dependency`. That should be fixed.

**Closed** 2024-09-16 19:05 UTC
Labels: bug
