### ISSUE TITLE
Enable go to definition from standard library files

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [zigtools/zls#257] opened 2021-03-25 08:14 UTC
When using Goto Definition on a std function, the corresponding file of the standard library is opened. In that file, however, the LSP features are not available, because the client figures the standard library files are not in scope of the session workspace. This is technically correct behavior, but somewhat frustrating for the user, who shouldn't need to (and, at least with Sublime Text, simply cannot) manually add the std lib folder to the workspace.

Is there any possibility of circumventing this?

**Comment by InterplanetaryEngineer** [comment] 2021-03-25 15:54
Maybe with a [window/showDocument](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#window_showDocument) request?

**Comment by alexnask** [comment] 2021-03-25 16:06
@InterplanetaryEngineer 
I have never encountered this issue in VSCode or kak (I think maybe one of the bugs I observed in coc.nvim was actually this issue though).  
What LSP client are you using?  
It would be nice to know so that I can debug and find a fix for this issue.  
Thanks for reporting and for your PR.

**Comment by InterplanetaryEngineer** [comment] 2021-03-25 17:04
I used https://github.com/sublimelsp/LSP .
Thank you for your responsiveness! zls is very useful to me and I would be glad to help with this however I can.

**Comment by alexnask** [comment] 2021-03-28 16:10
@InterplanetaryEngineer 
I am currently testing this on sublime text 3 with the LSP client and cannot reproduce.  
I seem to be able to navigate in the stdlib files fine.  

Is there any chance the symbol you were trying this on is simply not resolvable for zls (e.g. depends on some comptime evaluation)?  
If not, can you describe the way you get this behavior?

**Comment by InterplanetaryEngineer** [comment] 2021-03-28 16:26
Using Sublime Text version 3211-1, the latest Sublime-LSP release and zls build and zig 0.7.1, I
 * open a folder: `subl zls`
 * open `src/main.zig`
 * right click any symbol from the standard library, e. g. `std.log.scoped`, select `LSP -> Go To Symbol Definition`
 * `/usr/lib/zig/std/log.zig` opens, but all LSP actions are greyed out on every symbol and LSP key bindings do nothing.

My LSP.sublime-settings file contains
```
{
    "clients":
    {
        "zig":
        {
            "command":
            [
                "~/path/to/zls/zig-cache/bin/zls"
            ],
            "enabled": true,
            "languageId": "zig",
            "scopes":
            [
                "source.zig"
            ],
            "syntaxes":
            [
                "Packages/Zig Language/Syntaxes/Zig.tmLanguage"
            ]
        }
    }
}
```

**Comment by alexnask** [comment] 2021-03-28 16:29
Ah, I see, I was not opening a folder.  
Thanks, I can repro this now.

**Comment by alexnask** [comment] 2021-03-28 17:35
I think the issue is in this bit of code: https://github.com/sublimelsp/LSP/blob/f21bedfd06cb1be0e6fae13c85f85fdd0cb44b65/plugin/core/sessions.py#L193-L204

When opening a folder, the session will get assingned a single workspace folder even if the server does not support workspace folders.  
This results in `handles_path` always returning false for documents outside the folder.  

I'm honestly not sure if this bug is on the client or server side, I'm leaning towards the client since the server explicitly announces it does not support workspace folders in its capabilities.  
I will take a closer look at the specification to see if it clarifies this.

**Comment by InterplanetaryEngineer** [comment] 2021-03-28 20:04
I'd assume VSCode does the right thing here (because they founded the standard) − the spec does not seem not mention didOpen being restricted by workspaces at all.

**Comment by InterplanetaryEngineer** [comment] 2021-04-04 16:21
It sounds like the ST3 version of Sublime-LSP is [not getting fixes anymore](https://github.com/sublimelsp/LSP/issues/1634#issuecomment-813043169), so I'll wait for ST4 be released (hopefully soon!) and report back on this.

**Comment by rwols** [comment] 2021-04-04 19:13
> This results in handles_path always returning false for documents outside the folder.

That’s correct. There have been many, many discussions about this. Whether it is e.g. desirable to see linter warnings for files outside the project that you can’t do anything about. In the end, it was decided that the pros outweigh the cons and langservers are now attached to files outside the workspace regardless. This may result in undesirable linter warnings that you can’t do anything about. This change is contained in the ST4 branch, not in the ST3 branch.

**Comment by alexnask** [comment] 2021-04-04 22:38
Thanks for the clarification.

**Closed by alexnask** 2021-04-04 22:38 UTC
Labels: bug
