### ISSUE TITLE
Neovim lsp crashes when using latest zls

### ISSUE THREAD

**Issue by dmbfm** [zigtools/zls#867] opened 2022-12-30 19:35 UTC
### Zig Version

0.11.0-dev.1011+40ba4d4a8

### Zig Language Server Version

0.11.0-dev.97+c88562c

### Steps to Reproduce

Open any zig file in neovim with LSP enabled and 

### Expected Behavior

The servers should not crash.

### Actual Behavior

get this error message:

```
Error executing vim.schedule lua callback: ...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1278: RPC[Error] code_name = unknown, code = 104, message = "InternalError"
stack traceback:
        [C]: in function 'assert'
        ...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1278: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

LspLog outputs this:
```
[START][2022-12-30 16:32:01] LSP logging initiated
[ERROR][2022-12-30 16:32:01] .../vim/lsp/rpc.lua:733	"rpc"	"zls"	"stderr"	"info : ( main ): Enabled debug logging.\n\n"
[ERROR][2022-12-30 16:32:01] .../vim/lsp/rpc.lua:733	"rpc"	"zls"	"stderr"	"info : (config): Using zig executable /Users/daniel/.local/bin/zig\n"
[ERROR][2022-12-30 16:32:01] .../vim/lsp/rpc.lua:733	"rpc"	"zls"	"stderr"	"info : (config): Using zig lib path '/Users/daniel/.zigup/zig-macos-aarch64-0.11.0-dev.1011+40ba4d4a8/lib'\n"
[ERROR][2022-12-30 16:32:01] .../vim/lsp/rpc.lua:733	"rpc"	"zls"	"stderr"	"debug: (server): Took 1ms to process method initialize\n"
[ERROR][2022-12-30 16:32:01] .../vim/lsp/rpc.lua:733	"rpc"	"zls"	"stderr"	"error: (server): got error.InternalError while processing message!\n"

```
It seems that this happens after commit 61c0981294c52820d185afe41a0965a722c3e314. Previous commits seem to work correctly.

**Comment by LordMZTE** [comment] 2023-01-03 20:40
Can reproduce, I suspect its caused by this line: https://github.com/zigtools/zls/blame/master/src/Server.zig#L3049

**Comment by mlugg** [comment] 2023-01-05 18:41
Resolved by that PR - it's actually nvim that's at fault here (unless I'm misreading the LSP spec), but the workaround is pretty easy

**Closed** 2023-01-05 18:50 UTC
Labels: bug
