### ISSUE TITLE
ZLS crashes when typing above a doc string

### ISSUE THREAD

**Issue by bpeake13** [zigtools/zls#488] opened 2022-05-15 06:02 UTC
Im using ZLS with vscode. Whenever I begin typing  above a line with a comment, zls will crash. For example:
```
var t = 
// Comment
```
Would cause a crash

**Comment by SuperAuguste** [comment] 2022-07-08 08:57
Hey @bpeake13, I'm not able to reproduce this! Could you please test this on the latest commit of zls and tell me if this issue still persists? If it does, we can exchange editor info and proceed from there! Thanks!

**Comment by nektro** [comment] 2022-07-08 15:35
can confirm this used to happen to me and no longer does after pulling latest changes

**Comment by SuperAuguste** [comment] 2022-07-08 17:08
Thanks Meghan, good to know! I'll close this issue; please reopen if this occurs again! :)

**Closed by SuperAuguste** 2022-07-08 17:08 UTC
