### ISSUE TITLE
Build error zig master 8/20 release

### ISSUE THREAD

**Issue by sngeth** [zigtools/zls#2008] opened 2024-08-21 13:04 UTC
### Zig Version

0.14.0-dev.1217+dffc8c44f

### ZLS Version

cannot build

### Steps to Reproduce and Observed Behavior

1. Download 0.14.0-dev.1217+dffc8c44f of zig lang
2. Run `zig build -Doptimize=ReleaseSafe` in root `zls` project folder

### Expected Behavior

Project should build with no error

### Relevant log output

```shell
✘ sngeth@Sids-MBP  ~/Code/zls   master  zig build -Doptimize=ReleaseSafe
install
└─ install zls
   └─ zig build-exe zls ReleaseSafe native 1 errors
src/translate_c.zig:226:14: error: no field named 'emit_bin_path' in enum 'zig.Server.Message.Tag'
            .emit_bin_path => {
            ~^~~~~~~~~~~~~
/Users/sngeth/zig/lib/std/zig/Server.zig:12:21: note: enum declared here
    pub const Tag = enum(u32) {
                    ^~~~
referenced by:
    resolveCImport: src/DocumentStore.zig:1481:47
    resolveTypeOfNodeUncached: src/analysis.zig:1801:71
    16 reference(s) hidden; use '-freference-trace=18' to see all references
```

**Comment by Techatrix** [comment] 2024-08-21 14:34
This is caused by a recent breaking change in Zig. Will be fixed by #2007 when its ready.

**Closed** 2024-08-22 14:54 UTC
Labels: bug
