### ISSUE TITLE
crash when return type of a function pointer is missing

### ISSUE THREAD

**Issue by Hadron67** [zigtools/zls#298] opened 2021-04-05 12:14 UTC
zls from `902c91e`. This causes the crash:
```zig
const h: fn();
```
Also affects variable and struct member. Noticed this in the log:
```
Segmentation fault at address 0x0
```

**Comment by InterplanetaryEngineer** [comment] 2021-04-05 13:17
Cannot reproduce

**Comment by Hadron67** [comment] 2021-04-05 14:35
Perhaps I'm missing something. Steps to reproduce:
* create file `test.zig`;
* input `const h: f();`
Note that it works fine and just shows syntax error if that semicolon is missing.

I'm using `zig-linux-x86_64-0.8.0-dev.1721+c9ffb6f73` on Ubuntu 20.04.

**Comment by alexnask** [comment] 2021-04-05 14:35
Thanks for reporting, I have managed to reproduce this, on it :)

**Comment by alexnask** [comment] 2021-04-05 16:46
Closed in 4b0d86f0bcac2efaae70a7788b0688e53392faf0

**Closed by alexnask** 2021-04-05 16:46 UTC
Labels: bug
