### ISSUE TITLE
build from source error

### ISSUE THREAD

**Issue by mingodad** [zigtools/zls#2073] opened 2024-11-03 10:37 UTC
### Zig Version

0.14.0-dev.2106+ab89af3d3

### ZLS Version

b2e89dfe92850cf02cbd4b73004aaaecd5cf1739

### Steps to Reproduce and Observed Behavior

zig build -Doptimize=ReleaseSafe

### Expected Behavior

build without error

### Relevant log output

```shell
zig build -Doptimize=ReleaseSafe
install
+- install zls
   +- zig build-exe zls ReleaseSafe native 1 errors
src/binned_allocator.zig:21:13: error: non-comptime tuple field has default initialization value
```

**Comment by Or-Gold** [comment] 2024-11-03 14:17
This is a regression caused by [this commit removing anonymous struct literals](https://github.com/ziglang/zig/commit/d11bbde5f9c64ef58405604601d55f88bb5d5f3a).

Because anonymous struct literals are no longer a thing, Bins is registered as a tuple and cannot have default struct initializers.
The better solution (instead of adding comptime like this) is to make a function createBins that returns an initialized Bins
```zig
const Bins = struct {
        Bin(16, 8),
        Bin(64, 4),
        Bin(256, 2),
        Bin(1024, 0),
        Bin(4096, 0),
 }

fn createBins() Bins {
    return Bins{.{}, .{}, .{},.{}};
}
```

Most of the other issues can be trivially fixed by providing a concrete type, by replacing `const a = .{} ` with `const a = SomeStruct{}` or with `const a: SomeStruct = .{}`.

The complicated fix (which I am not familliar enough with the codebase to figure out) is to fix the errors in the generated code from `config_gen` and the likes, by providing concrete types for the generated types.

**Closed** 2024-11-03 15:10 UTC
Labels: bug

**Comment by mingodad** [comment] 2024-11-03 15:36
Thank you !
