### ISSUE TITLE
CompletionItems not sorted when falls back to fuzzy search

### ISSUE THREAD

**Issue by ryuukk** [zigtools/zls#1164] opened 2023-05-02 02:01 UTC
### Zig Version

zig-0.11.0-dev.2935+ec6ffaa1e.tar.xz

### Zig Language Server Version

the one from vscode, i don't know how to check the version

### Steps to Reproduce

Try to get completion for anything and trigger fuzzy search

### Expected Behavior

CompletionItems should be sorted, kind contained together

### Actual Behavior

![image](https://user-images.githubusercontent.com/44361234/235563931-294054ad-7d2b-457d-b9d4-d5b014e76c67.png)

![image](https://user-images.githubusercontent.com/44361234/235563584-23200364-7fd3-4d4e-b0be-923222de72ee.png)

**Comment by Techatrix** [comment] 2023-05-14 20:23
This fuzzy search is not part of ZLS but rather a feature of VS-Code. I was not able to find a setting that would prevent this behavior. Perhaps opening an issue on [VS-Code](https://github.com/microsoft/vscode/issues) would be appropriate.

**Comment by Techatrix** [comment] 2023-07-28 01:32
> This fuzzy search is not part of ZLS but rather a feature of VS-Code.

Based on my previous comment I will be closing this issue since this does not seem to be the caused by ZLS.

**Closed by Techatrix** 2023-07-28 01:32 UTC
Labels: bug
