### ISSUE TITLE
Goto definition doesn't work for the first character in an identifier 

### ISSUE THREAD

**Issue by matklad** [zigtools/zls#899] opened 2023-01-09 15:48 UTC
![image](https://user-images.githubusercontent.com/1711539/211348096-7a58588e-6e78-4399-b0d2-05ea7c072611.png)

If I move the cursor to `o`, this works, so this is an "off-by-one" kind of bug. 

In general, handling this correctly is a bit tricky, because block and line cursors have somewhat different semantics (line is between positions, block is on a position). 

The logic rust-analyzer uses here: 

* "get token at offset" operations takes a numerical offset, and returns zero, one, or two tokens at the given offset (so, losslessly handle the casses where the cursor is genuineely between two tokesn)
* than, a feature specific utility picks the "best" token (eg, idents over keywords over punctuation over whitespace)
* all the latter functionality (goto def and such) works with a token, rather than with an offset.

**Comment by SuperAuguste** [comment] 2023-01-09 16:14
Duplicate of #891

**Closed by SuperAuguste** 2023-01-09 16:14 UTC
