### ISSUE TITLE
completion broken on emacs

### ISSUE THREAD

**Issue by g-w1** [zigtools/zls#268] opened 2021-03-29 18:35 UTC
With some of the new changes, I get a completion menu on pressing `.`:
![image](https://user-images.githubusercontent.com/58830309/112883047-c424aa80-909b-11eb-861b-8d6788a5c651.png)
But then it goes away when I type. 
![image](https://user-images.githubusercontent.com/58830309/112883090-cd157c00-909b-11eb-91d8-89ea0970a61b.png)
This happens on emacs, but not on neovim. I think it could be this commit https://github.com/zigtools/zls/commit/bd3f0460bad6212053bce786f4ac73d05db609f9

**Comment by alexnask** [comment] 2021-03-29 22:27
Hey, currently trying to reproduce this.  

This is what I tried:
- Start with a fresh emacs install
- Install zig-mode, lsp-mode, company 
- Launch emacs with `zls` in PATH (this allows us to skip any lsp-mode configuration since a default zls config was added)
- Open a file, run  `M-x lsp`
- Type away

![image](https://user-images.githubusercontent.com/265903/112907405-75582e80-90f6-11eb-8f72-7d0ffa680df0.png)

**Comment by g-w1** [comment] 2021-03-29 23:10
Let me try that. If I cannot get it to work ill close this issue.

**Comment by g-w1** [comment] 2021-03-29 23:20
Ok, it seems like something with my setup as it is now breaking on older versions :(. Closing

**Comment by g-w1** [comment] 2021-04-04 19:11
Upstream issue: https://github.com/emacs-lsp/lsp-mode/issues/2761

**Comment by bnjmnt4n** [comment] 2021-04-05 07:30
Actually, given that `filterText` isn't really used, what do you think about just removing `filterText` from the response? The only instance where it is used is providing completions for builtin functions `@X`, and it merely removes the `@` from the function name (https://github.com/zigtools/zls/blob/42aefd2e679b1e55e86453ce8fea236db724afa8/src/main.zig#L1063-L1072). I'm not too sure if there's a difference between including the `@` in the `filterText` or not (filtering completions work fine for me in lsp-mode without the `filterText`), so if there's no difference, and there are no plans to use `filterText` to provide a different filter text than the label, then removing the `filterText` from the response should be fine. That will also allow completion responses to be shorter (just a really minor difference, but perhaps it might add up over time).

**Comment by alexnask** [comment] 2021-04-05 09:06
Sorry about the inconvenience, I somehow thought the bug was that completions didn't show up at all.  
It seems like sending a null filterText fixes this for emacs lsp-mode (altough an empty string should work per the specs, any falsy filterText value should result in using the insertText to filter instead)  

Closed in d397f1119e40dd22b7e3553fd90bc104e6cd1403

**Closed by alexnask** 2021-04-05 09:06 UTC
Labels: bug

**Comment by bnjmnt4n** [comment] 2021-04-05 09:25
Thanks for the quick response @alexnask! Actually, this has just been fixed in lsp-mode upstream (https://github.com/emacs-lsp/lsp-mode/pull/2762), so you can actually revert to the original spec behaviour if desired. (Sorry for this revert dance).

My comment above (https://github.com/zigtools/zls/issues/268#issuecomment-813245421) was actually referring to just completely removing the `filterText` field from the response, since it seems to be largely unused, although that's also not very important.

**Comment by alexnask** [comment] 2021-04-05 09:27
@bnjmnt4n No worries, sending null is als correct :)  
The LSP spec spicifially marks the fields that can be omitted, filterText is not one of them.  

Thanks anyway, glad this is now non issue for people that don't regularly recompile for zls master as wll :)
