### ISSUE TITLE
c import causes zls to stop functioning

### ISSUE THREAD

**Issue by leecannon** [zigtools/zls#1082] opened 2023-03-20 18:35 UTC
### Zig Version

0.11.0-dev.2191+30427ff79

### Zig Language Server Version

0.11.0-dev.332+a929576

### Steps to Reproduce

I don't know whether this is libgit2 specific but that is what im experiencing this with.

1. `zig init-exe`
2. add `exe.linkLibC();`  to build.zig
3. add `exe.linkSystemLibrary("git2");`  to build.zig
4. make main.zig:
```zig
const c = @cImport({
    @cInclude("git2.h");
});

const std = @import("std");

fn func() void {}
```
5. type `std.` in `func`, completions will show fine
6. delete `std.` and type `c.` no completions show
7. delete `c.` and type `std.` no completions show

### Expected Behavior

ZLS not to die

### Actual Behavior

It seems like ZLS stops responding completely as completeions, hover, formating and everything else stops and there are no more messages in vscode output.

**Comment by SuperAuguste** [comment] 2023-03-20 18:47
Duplicate of #1080

**Closed by SuperAuguste** 2023-03-20 18:47 UTC
Labels: bug
