### ISSUE TITLE
Seemingly random enum members appear when you press `.`

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#937] opened 2023-01-24 09:19 UTC
### Zig Version

0.11.0-dev.1393+38eebf3c4

### Zig Language Server Version

48288e02a9a5d0ba4ef5be1db7be6a64d37d2806

### Steps to Reproduce

Code:
```zig
const std = @import("std");

const CacheConfig2 = union(enum) {
    hi2: u12,
    h3ey: u123,
    hello4: u1234,
};

const CacheConfig = union(enum) {
    hi: u12,
    hey: u123,
    hello: u1234,
};

fn hey() CacheConfig {
    return .
    //     ^--------- This line 
}

pub fn main() anyerror!void {
    std.debug.print("{any}", .{try hey()});
}


```

### Expected Behavior

<img width="532" alt="image" src="https://user-images.githubusercontent.com/709451/214253526-241985be-f800-4b8a-b1fb-51c6eece28fb.png">

### Actual Behavior

<img width="662" alt="image" src="https://user-images.githubusercontent.com/709451/214253329-6b3bed2d-3c9b-46c6-b2a4-7e71f11395fa.png">

**Comment by SuperAuguste** [comment] 2023-01-24 15:16
Duplicate of #376.

**Closed by SuperAuguste** 2023-01-24 15:16 UTC
Labels: bug
