### ISSUE TITLE
No C++ code completion on master branch

### ISSUE THREAD

**Issue by DasGandlaf** [zigtools/zls#1970] opened 2024-07-22 21:34 UTC
### Zig Version

0.14.0-dev.367+a57479afc

### Zig Language Server Version

3b9216e4444395ab1ee35911e9927571f8291fad

### Client / Code Editor / Extensions

nvim 0.10 with lsp (nvim-lspconfig)

### Steps to Reproduce and Observed Behavior

I use:
```zig
const rl = @cImport({
    @cInclude("raylib.h");
});
```

`rl.` does not autocomplete anything.

### Expected Behavior

Autocompletion should work.

(It does work in the official zls 0.13.0 release, but not on the current master)

**Comment by DasGandlaf** [comment] 2024-07-24 07:03
I don't think the problem is with Raylib. When I use the official 13.0 zls release, there is code completion without any issues. Only on master there is none.

I built Raylib with cmake to a .dll linked with a static .lib file.

The log is definitely worth checking out, I'll let you know when I have any new info ;)

And thanks for the `raylib-zig` suggestion!

**Comment by nothke** [comment] 2024-07-29 10:05
Can confirm C autocompletion doesn't work, I used it with sokol and cimgui, and just struggled with this for almost 2 hours on stream ([starting here](https://www.twitch.tv/videos/2209871922?t=0h24m37s)) to realize that it was zls master's fault because when I switched to 0.13 it worked just fine.

**Comment by weskoerber** [comment] 2024-08-06 00:14
I can't get `@cInclude`s to work, either. I think my issue is specific to non-system, relative paths.

- Including system headers (e.g. "curl/curl.h") works fine.
- Including local headers via relative path (e.g. "relative/path/to/header.h") does not work.
    - Yes, I've added the include path in `build.zig` via `b.addIncludePath`
- Including local headers via absolute path (e.g. "/absolute/path/to/headers.h") does work. 

I'm not sure if this is the same issue or not. If my comment doesn't belong here, I'm happy to open up a new issue :)

**Comment by Techatrix** [comment] 2024-08-06 00:48
> I'm not sure if this is the same issue or not. If my comment doesn't belong here, I'm happy to open up a new issue :)

Please open a new issue and provide as much information about your environment as possible. Zig version, ZLS version, the `build.zig` file, ZLS log output, etc. Without them I would need to do a lot of guesswork to figure out what is going on.

**Comment by Techatrix** [comment] 2024-08-06 01:06
> You could provide more detailed information on how you have installed/setup raylib?

Since this request has not been met, I have no way of reproducing/investigating this issue. So I'm assuming this is the same problem that caused #1985 which was fixed by #1983.

If there is still an issue with cImport, feel free to open a new issue.

**Closed by Techatrix** 2024-08-06 01:06 UTC
Labels: bug

**Comment by weskoerber** [comment] 2024-08-06 18:48
> > I'm not sure if this is the same issue or not. If my comment doesn't belong here, I'm happy to open up a new issue :)
> 
> Please open a new issue and provide as much information about your environment as possible. Zig version, ZLS version, the `build.zig` file, ZLS log output, etc. Without them I would need to do a lot of guesswork to figure out what is going on.

My issue was totally unrelated, and entirely caused my me. Apologies for the noise...
