### ISSUE TITLE
Incorrect ArrayList items completions when ArrayLists nested

### ISSUE THREAD

**Issue by SuperAuguste** [zigtools/zls#1649] opened 2023-12-04 06:37 UTC
### Zig Version

0.12.0-dev.1769+bf5ab5451

### Zig Language Server Version

0.12.0-dev.280+b328500

### Steps to Reproduce

```zig
const std = @import("std");

test {
    const C = struct {a: u8};
    const a = std.ArrayList(std.ArrayList(C)).init(undefined);
    a.items[0].
}
```

### Expected Behavior

`ArrayList(C)` children shown.

### Actual Behavior

Children of `C` shown.

**Comment by Techatrix** [comment] 2023-12-09 04:18
duplicate of #1392

**Closed by Techatrix** 2023-12-09 04:18 UTC
Labels: bug
