### ISSUE TITLE
Zls shows incorrect types with nested ArrayLists

### ISSUE THREAD

**Issue by tymbaca** [zigtools/zls#1686] opened 2023-12-24 11:26 UTC
### Zig Version

0.11.0

### Zig Language Server Version

0.11.0

### Client / Code Editor / Extensions

nvim v0.9.4 + lsp (zls)

### Steps to Reproduce and Observed Behavior

Put this code in a `.zig` file.
```zig
const std = @import("std");
const eql = std.mem.eql;
const print = std.debug.print;
const log = std.log;
const ArrayList = std.ArrayList;

pub const HashSet = struct {
    buckets: Buckets,
    allocator: std.mem.Allocator = std.heap.page_allocator,

    pub fn init() !HashSet {
        var hs = HashSet{ .buckets = undefined };

        hs.buckets = Buckets.init(hs.allocator);
        for (0..4) |_| {
            log.debug("Created bucket", .{});
            var buck = Bucket.init(hs.allocator);
            try hs.buckets.append(buck);
        }

        return hs;
    }

    pub fn add(self: *HashSet, val: String) !void {
        var h = hash(val);
        var bucket_index = h % self.buckets.items.len;
        var bucket = self.buckets.items[bucket_index];

        for (bucket.items) |item| {
            if (eql(u8, item, val)) {
                return Error.AlreadyAdded;
            }
        }
    }

    pub fn get(self: *HashSet, val: []const u8) void {
        _ = self;
        _ = val;
    }

    pub fn remove(self: *HashSet, val: []const u8) void {
        _ = self;
        _ = val;
    }

    fn hash(val: []const u8) u64 {
        _ = val;
        return 65;
    }
};

const Buckets = ArrayList(Bucket);
const Bucket = ArrayList(String);
const String = []const u8;

const Error = error{
    AlreadyAdded,
};

test "init" {
    var h = try HashSet.init();

    for (h.buckets.items) |item| {
        print("bucket: {any}\n", .{item});
    }
}

test "add" {
    var h = try HashSet.init();
    try h.add("val");
}

```

### Expected Behavior

I expect that at line 27 zls will tell me that `bucket` is a type of `ArrayList([]const u8)`. 

But it shows me that `bucket` has a type `[]const u8`, NOT AN `ArrayList`.

![Screenshot_1](https://github.com/zigtools/zls/assets/59094569/936e0f4d-81ba-4148-a909-b8f32a90ef9f)

P.s. Code compiles and works how expected, only zsl works incorrectly

### Relevant log output

```shell
There is a log from `LspLog`:


[ERROR][2023-12-24 13:17:24] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"info : ( main ): Starting ZLS 0.11.0 @ '/home/tymbaca/.local/share/nvim/mason/bin/zls'\ninfo : ( main ): No config file zls.json found.\ninfo : (config): Using zig executable '/home/linuxbrew/.linuxbrew/bin/zig'\n"
[ERROR][2023-12-24 13:17:24] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"info : (config): Using zig lib path '/home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig'\ninfo : (config): Using build runner global cache path '/home/tymbaca/.cache/zig'\ninfo : (config): Detected runtime zig version: '0.11.0'\n"
[ERROR][2023-12-24 13:17:24] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"info : (server): client is 'Neovim-0.9.4'\ninfo : (server): zls initializing\ninfo : (server): Server.ClientCapabilities{ .supports_snippets = true, .supports_apply_edits = true, .supports_will_save = true, .supports_will_save_wait_until = true, .supports_publish_diagnostics = true, .supports_code_action_fixall = false, .hover_supports_md = true, .completion_doc_supports_md = true, .label_details_support = true, .supports_configuration = true, .supports_workspace_did_change_configuration_dynamic_registration = false, .supports_textDocument_definition_linkSupport = true }\ninfo : (server): Using offset encoding: utf-16\n"
[ERROR][2023-12-24 13:17:24] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 0ms to process request-1-initialize on Thread 44107\n"
[ERROR][2023-12-24 13:17:24] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 0ms to process notification-initialized on Thread 44107\n"
[ERROR][2023-12-24 13:17:24] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 1ms to process notification-textDocument/didOpen on Thread 44107\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 1ms to process notification-textDocument/didOpen on Thread 44107\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/std.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/std.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/debug.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/io.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/mem.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/log.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/fs.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/array_list.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/mem/Allocator.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/fs/file.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/heap.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/io/writer.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 118ms to process request-2-textDocument/semanticTokens/full on Thread 44111\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/os.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (store ): Opened document `file:///home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig/std/io/buffered_writer.zig`\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 157ms to process request-3-textDocument/semanticTokens/full on Thread 44108\ninfo : (server): Setting configuration...\ndebug: (server): Server.ClientCapabilities{ .supports_snippets = true, .supports_apply_edits = true, .supports_will_save"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	" = true, .supports_will_save_wait_until = true, .supports_publish_diagnostics = true, .supports_code_action_fixall = false, .hover_supports_md = true, .completion_doc_supports_md = true, .label_details_support = true, .supports_configuration = true, .supports_workspace_did_change_configuration_dynamic_registration = false, .supports_textDocument_definition_linkSupport = true }\ninfo : (config): Using zig executable '/home/linuxbrew/.linuxbrew/bin/zig'\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"info : (config): Using zig lib path '/home/linuxbrew/.linuxbrew/Cellar/zig/0.11.0/lib/zig'\ninfo : (config): Using build runner global cache path '/home/tymbaca/.cache/zig'\ninfo : (config): Detected runtime zig version: '0.11.0'\n"
[ERROR][2023-12-24 13:17:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 6ms to process response-i_haz_configuration on Thread 44107\n"
[ERROR][2023-12-24 13:17:26] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 1ms to process request-4-textDocument/hover on Thread 44109\n"
[ERROR][2023-12-24 13:17:28] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 1ms to process request-5-textDocument/hover on Thread 44110\n"
[ERROR][2023-12-24 13:20:49] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 1ms to process notification-textDocument/didChange on Thread 44107\n"
[ERROR][2023-12-24 13:20:49] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 3ms to process request-6-textDocument/semanticTokens/full on Thread 44110\n"
[ERROR][2023-12-24 13:20:50] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 2ms to process notification-textDocument/didChange on Thread 44107\n"
[ERROR][2023-12-24 13:20:50] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 2ms to process notification-textDocument/didChange on Thread 44107\n"
[ERROR][2023-12-24 13:20:50] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 0ms to process notification-textDocument/willSave on Thread 44109\n"
[ERROR][2023-12-24 13:20:50] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 11ms to process request-7-textDocument/willSaveWaitUntil on Thread 44110\n"
[ERROR][2023-12-24 13:20:50] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 0ms to process notification-textDocument/didSave on Thread 44107\n"
[ERROR][2023-12-24 13:20:50] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 2ms to process request-8-textDocument/semanticTokens/full on Thread 44111\n"
[ERROR][2023-12-24 13:22:41] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 1ms to process request-9-textDocument/hover on Thread 44109\n"
[ERROR][2023-12-24 13:22:44] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 1ms to process request-10-textDocument/hover on Thread 44108\n"
[ERROR][2023-12-24 13:23:31] .../vim/lsp/rpc.lua:734	"rpc"	"/home/tymbaca/.local/share/nvim/mason/bin/zls"	"stderr"	"debug: (server): Took 1ms to process request-11-textDocument/hover on Thread 44111\n"
```

**Comment by leecannon** [comment] 2023-12-24 11:57
Duplicate of https://github.com/zigtools/zls/issues/1392

**Closed by leecannon** 2023-12-24 11:57 UTC
Labels: bug
