### ISSUE TITLE
Switch in cImport crashing with "reached unreachable code"

### ISSUE THREAD

**Issue by candrewlee14** [zigtools/zls#1086] opened 2023-03-21 02:13 UTC
### Zig Version

0.11.0-dev.2191+30427ff79

### Zig Language Server Version

Latest VSCode version

### Steps to Reproduce

Try running something like this:
```zig
const builtin = @import("builtin");
const Opts = struct {
    use_blas: bool = false,
};
const opts = .{.use_blas = false};
// the problem
const c = if (opts.use_blas) @cImport(
    switch (builtin.os.tag) {
         .linux, .windows => @cInclude("cblas.h"),
         .macos => @cInclude("Accelerate/Accelerate.h"),
         else => @compileError("Unsupported OS"),
}) else void;
```

### Expected Behavior

Not panic

### Actual Behavior

ZLS crashes with "reached unreachable code"

**Comment by candrewlee14** [comment] 2023-03-21 02:14
There is a workaround, though it forces code duplication for all the common imports:
```zig
const c = if (opts.use_blas)
    switch (builtin.os.tag) {
        .linux, .windows => @cImport(@cInclude("cblas.h")),
        .macos => @cImport(@cInclude("Accelerate/Accelerate.h")),
        else => @cImport(@compileError("Unsupported OS")),
    } else void;
```

**Comment by SuperAuguste** [comment] 2023-03-24 01:51
Duplicate of #1080 I imagine.

**Closed by SuperAuguste** 2023-03-24 01:51 UTC
Labels: bug
