### ISSUE TITLE
Incorrect type definition from nested hash maps.

### ISSUE THREAD

**Issue by gubsey** [zigtools/zls#1963] opened 2024-07-18 16:02 UTC
### Zig Version

0.14.0-dev.349+e82f7d380

### Zig Language Server Version

0.14.0-dev.363

### Client / Code Editor / Extensions

vscode with the zig extension

### Steps to Reproduce and Observed Behavior

The following code will give an incorrect type definition from ZLS. `x` is supposed to be a hash map, but ZLS labels it as an `i32`.
```zig
const std = @import("std");

test {
    const map = std.StringHashMap(std.StringHashMap(i32)).init(std.testing.alloc);
    const x = map.get("").?;
    _ = x;
}
```

### Expected Behavior

ZLS should label variables with the right type definition.

**Comment by Techatrix** [comment] 2024-07-18 21:12
Duplicate of #1392

**Closed by Techatrix** 2024-07-18 21:12 UTC
Labels: bug
