### ISSUE TITLE
Zls gives wrong type information for nested for loops

### ISSUE THREAD

**Issue by temhelk** [zigtools/zls#1819] opened 2024-03-05 13:38 UTC
### Zig Version

0.12.0-dev.3154+0b744da84

### Zig Language Server Version

0.12.0-dev.480+dd307c59

### Client / Code Editor / Extensions

latest Neovim and latest vs code show the same behavior

### Steps to Reproduce and Observed Behavior

Create a `main.zig` file with the following content:
```zig
const std = @import("std");

const A = struct {
    bs: std.ArrayList(B),
};

const B = struct {
    cs: std.ArrayList(C),
};

const C = struct {
};

pub fn main() !void {
    const a: A = undefined;

    for (a.bs.items) |b| {
        for (b.cs.items) |c| {
            _ = c; // autofix
        }
    }
}
```

Then check the type information for the `c` variable inside the nested loop, it should have the type `C` but in fact zls says it's of the type `B`:
![image](https://github.com/zigtools/zls/assets/77777950/cb3d5e2e-8282-4540-973a-3fb5f7226200)
(Neovim)
![image](https://github.com/zigtools/zls/assets/77777950/288496ef-d8b2-4e72-b59c-ddc9a52fb857)
(vs code)

The `cs` field of `b` is correctly typed:
![image](https://github.com/zigtools/zls/assets/77777950/765753b0-a5c8-447e-bb0c-424b77608c3c)
But the problem starts with the field `items` of ArrayList `cs`:
![image](https://github.com/zigtools/zls/assets/77777950/a6ee0af3-5579-4834-a33f-89909a00cf20)

### Expected Behavior

The type information should be correct

**Comment by Techatrix** [comment] 2024-03-05 13:42
Duplicate of #1392

**Closed by Techatrix** 2024-03-05 13:42 UTC
Labels: bug
